[package]
name = "storage"
version = "0.1.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
edition = "2021"

[dependencies]
storage_derive = { path = "./derive" }
sled = "0.34"
serde = {version = "1", features = ["derive"]}
bincode = "1.3"
