sender_interval = 10
validator_interval = 10
storage_path = "record_db"
auto_api_url = "http://124.71.204.213"
# Be consistent with data_for_send.timeout
validator_timeout = 120
chain_for_send = [
    "cita-cloud-test",
    "cita-test",
]
data_for_send = """{
"to": "0x1879C8B68c50A4D4eeC9852325d32B60B43f3FbD",
"data": "0xabcd1234",
"timeout": 120
}"""

[log_config]
max_level = "debug"
# filter = "debug"
filter = "debug,hyper=info,opendal=info,sled=info,reqwest=info"
