sender_interval = 30
checker_interval = 10
log_filter = "info,hyper=warn"
storage_path = "record_db"
cache_url = "http://192.168.10.120:32667"
data_for_send = [
    """{
    "data": "",
    "quota": 20000,
    "to": "0xdc64666ff929994e5ee1131381d1d3f8693d3dab",
    "value": "0x1"
    }""",
]